### ISSUE TITLE
I am trying to locally deploy the site. I installed ruby, python 3, gem, and git. I changed the "remote_data_prefix" as my data repo url but when I run bundle exec jekyll serve I get invalid _sass folder issues and  Site config must include "remote_data_prefix" issue. 

### ISSUE THREAD

**Issue by MeghaStha** [open-sdg/open-sdg#1905]
**Please complete the following information** 
Site repository URL: https://github.com/MeghaStha/site/blob/develop/_data/site_config.yml

**Describe the bug**
When I run "bundle exec jekyll serve", I get  Generating...
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
Site config must include "remote_data_prefix". error. 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser:Chrome

![image](https://user-images.githubusercontent.com/9130639/208999550-66f21a9b-9dde-49d9-b3c9-3818f6e42f2b.png)
![image](https://user-images.githubusercontent.com/9130639/208999589-8f9a2887-f108-4beb-a7e7-426d44530d10.png)

**Comment by MeghaStha** [comment]
I solved this by adding remote_data_prefix to the _config.yml file but now I am getting another error 
PS C:\Users\megha\Box\1Megha\Dissertation\5.Objective 3\git\open-sdg-site-starter> bundle exec jekyll serve
Configuration file: C:/Users/megha/Box/1Megha/Dissertation/5.Objective 3/git/open-sdg-site-starter/_config.yml
            Source: C:/Users/megha/Box/1Megha/Dissertation/5.Objective 3/git/open-sdg-site-starter
       Destination: C:/Users/megha/Box/1Megha/Dissertation/5.Objective 3/git/open-sdg-site-starter/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Invalid theme folder: _sass
      Remote Theme: Using theme open-sdg/open-sdg
jekyll 3.8.4 | Error:  undefined method `append' for nil:NilClass

Both data and site starter are build upon gh-pages. 

You can see them here: https://github.com/MeghaStha/open-sdg-site-starter/blob/develop/_config.yml
https://github.com/MeghaStha/open-sdg-data-starter/settings/pages

**Comment by btylerburton** [comment]
Hi @MeghaStha, try adding a languages block to the `_config.yml`, like this:
```
languages:
  - en
  - es
```

and that should allow you to build the site.

**Comment by MeghaStha** [comment]
Thank you @btylerburton for the reply. Adding languages block solved the jekyll 3.8.4 | Error: undefined method `append' for nil:NilClass issue but now I am getting Invalid argument @ rb_sysopen - https://meghastha.github.io/AuburnAldataRepo/en/meta/all.json issue. I am working with ruby version 3.1.3. Is that the issue?

**Comment by btylerburton** [comment]
I'm not able to get it to build with anything beyond `2.7.7`. I haven't dug into what would need to be refactored to support v3.x.x.

**Comment by MeghaStha** [comment]
Thank you for the answer. I will reinstall ruby and try again.
